Adding changelog
pydantic/logfire pull request #245
Opened 2024-06-05 15:27 UTC by sydney-runkle

Fix https://github.com/pydantic/logfire/issues/237

2024-06-05 15:41 UTC, Kludex commented
Can we add the changelog to the docs, like this: https://github.com/encode/uvicorn/blob/master/docs/release-notes.md ?

Or just have the changelog on the docs itself?

2024-06-05 15:56 UTC, sydney-runkle commented
Please review

2024-06-07 06:57 UTC, Kludex requested changes

2024-06-07 06:57 UTC, Kludex commented on .github/workflows/check_changelog.yml
> +          done
You don't need to install toml on python 3.12 to read TOML files, you can use https://docs.python.org/3/library/tomllib.html, which is available from 3.11.

2024-06-07 06:57 UTC, Kludex commented
Feel free to merge it after removing the toml dependency 👍

2024-06-07 15:27 UTC, merged