wip live page update
pydantic/logfire pull request #632
Opened 2024-11-28 18:48 UTC by ChristopherGS

2024-11-29 09:05 UTC, ChristopherGS commented on docs/guides/web-ui/live.md
> -6. **Organization selection panel:** Opens a drawer with links to the different organizations you are a member of, and also has links to the Terms and Conditions, Support, Documentation, and a Log Ou
I've deliberately culled a lot of these - some are no longer relevant, but the section is currently just a bit too much of a "wall of text". I've tried to pull out the key/least intuitive areas to describe

2024-12-17 17:27 UTC, summerscope requested changes
@ChristopherGS I'm going to finish my review and instead just go ahead and commit my changes to your PR to speed this up 👍

2024-12-17 17:27 UTC, summerscope commented on docs/guides/web-ui/live.md
> +The live view is a central part of **Logfire**, where you can see traces in real-time.
```suggestion
The live view is the focal point of **Logfire**, where you can see traces arrive in real-time.
```

2024-12-17 17:27 UTC, summerscope commented on docs/guides/web-ui/live.md
> +To view the search box, click on `Search your spans` (keyboard shortcut `/`), this
```suggestion
To search the live view, click `Search your spans` (keyboard shortcut `/`), this
```

2024-12-17 17:27 UTC, summerscope commented on docs/guides/web-ui/live.md
> +will open the search box:
```suggestion 
opens the search pane:
```

2024-12-17 17:27 UTC, summerscope commented on docs/guides/web-ui/live.md
> +## The Live View Search
```suggestion
## SQL search pane
```

2024-12-17 17:27 UTC, summerscope commented on docs/guides/web-ui/live.md
> +application in real-time (as the name suggests), but it can also be used to explore historical data via the *live view search*.
```suggestion
application in real-time (as the name suggests). You can also explore historical data in the **search pane**.
```

2024-12-17 17:35 UTC, summerscope commented on docs/guides/web-ui/live.md
> +shortcut `cmd+enter` (or `ctrl+enter` on windows/linux).
```suggestion
For confident SQL users, write your queries directly here. For devs who want a bit of help, try the new [PydanticAI](https://ai.pydantic.dev/) feature which generates a SQL query based on your prompt. You can also review the fields available and populate your SQL automatically using the `Reference` list, see more on this below.

**
As the greyed out `SELECT * FROM RECORDS WHERE` implies, you're searching inside the `WHERE` clause of a SQL query. It has auto-complete & schema hints, so try typing something to get a reminder. To run your query click `Run` or keyboard shortcut `cmd+enter` (or `ctrl+enter` on windows/linux).
```

2024-12-17 18:00 UTC, summerscope approved these changes
ok @ChristopherGS please ignore my ugly commit history - made some edits to this copy to reflect latest changes, I think we will probably want to improve this more at some point but let's not let perfect be the enemy of better. FYI we should hold off on merging this PR until we make the new SQL editor the default mode - @petyosi could you merge this bad boy once that has happened?

2024-12-18 19:48 UTC, merged